### ISSUE TITLE
get trades failing with 401

### ISSUE THREAD

**Issue by npomfret** [QuoineFinancial/api_code_examples_client#1]
I'm getting a 401 returned from both `/trades` and `/executions/me`.  The body of the 401 response has the text  _Path does not match _.  The keys I'm using have full permissions.

**Comment by o0khoiclub0o** [comment]
@npomfret It means path in payload was wrong. Please check if path is '/traders' or '/executions/me' or not?

**Comment by npomfret** [comment]
thanks.
